using System;

public class Quicktype2
{
    public Quicktype2()
    {
    }
}
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var site = Site.FromJson(jsonString);

namespace QuickType2
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AddressClass
    {
        [JsonProperty("packedAddress")]
        public EdAddress PackedAddress { get; set; }

        [JsonProperty("validatedAddress")]
        public EdAddress ValidatedAddress { get; set; }

        [JsonProperty("standardAddress")]
        public string StandardAddress { get; set; }

        [JsonProperty("rawAddress")]
        public string RawAddress { get; set; }

        [JsonProperty("errors")]
        public List<object> Errors { get; set; }
    }

    public partial class EdAddress
    {
        [JsonProperty("Address1")]
        public string Address1 { get; set; }

        [JsonProperty("Address2")]
        public string Address2 { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("Zip5")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Zip5 { get; set; }

        [JsonProperty("Zip4")]
        public string Zip4 { get; set; }

        [JsonProperty("LocationId")]
        public string LocationId { get; set; }

        [JsonProperty("SublocationId")]
        public string SublocationId { get; set; }
    }

    public partial class AddressClass
    {
        public static AddressClass FromJson(string json) => JsonConvert.DeserializeObject<AddressClass>(json, QuickType2.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this AddressClass self) => JsonConvert.SerializeObject(self, QuickType2.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
